### PR TITLE
Changed code to read from gitignore.io

### PR DESCRIPTION
**Pull request by ChetanKoneru**
@xuchunyang 
Again Thanks for the code. I am able to get it working. 
Please accept this pull request if you think it's a good idea to use gitignore.io

### CODE REVIEW

**Comment by xuchunyang** [comment]
Not sure how to deal with this. As the GitHub API is still working, and it and gitignore.io are two different APIs. We can support them both easily, though a user option should be added to choose one of them (which one is the default can be discussed), is this solution ok with you?

**Comment by ChetanKoneru** [comment]
> Not sure how to deal with this. As the GitHub API is still working, and it and gitignore.io are two different APIs. We can support them both easily, though a user option should be added to choose one of them (which one is the default can be discussed), is this solution ok with you?

Sounds good. I am very new to elisp , While I understood the code and able to make modifications to it your package with your help , I am open to give this enhancement a go.

**Comment by xuchunyang** [comment]
Your commit 4b093e52f9c6ec3ba67da8f5e3e2f7d88aa24f89 is merged. gitignore.io is now supported and used as the default API. In case someone want GitHub API back, please add this to your init file.

``` emacs-lisp
(setq gitignore-templates-api 'github)
```

**Comment by ChetanKoneru** [comment]
@xuchunyang Thank you for doing this.

**Pull request closed without merging**
